-- ============================================================
-- Semester rollover + soft-delete migration
-- Run this in the Supabase SQL editor before using:
--   • Remove / restore semester (Routine Management hub)
--   • Create-semester rollover (archive to course history)
-- ============================================================

-- 1. Soft-delete support for academic semesters
ALTER TABLE academic_semesters
  ADD COLUMN IF NOT EXISTS is_removed boolean NOT NULL DEFAULT false;

ALTER TABLE academic_semesters
  ADD COLUMN IF NOT EXISTS removed_at timestamptz;

-- 2. Per-semester course teaching history (written on rollover).
--    Denormalized (code / title / teacher names copied in) so history
--    survives even if a course or teacher is later deleted.
CREATE TABLE IF NOT EXISTS course_history (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id      text NOT NULL,
  course_code    text,
  course_title   text,
  semester_label text NOT NULL,          -- e.g. 'Spring 2026'
  teacher_ids    jsonb NOT NULL DEFAULT '[]'::jsonb,
  teacher_names  jsonb NOT NULL DEFAULT '[]'::jsonb,
  archived_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_course_history_course
  ON course_history (course_id);
